name: NeurIPS Workshop on Muslims in ML
markdown: kramdown

navigation:
- text: Description
  url: /
- text: Talks 
  url: /talks/
- text: Schedule 
  url: /schedule/
- text: Registration 
  url: /registration/
- text: Call for Abstracts 
  url: /cfp/
- text: Organizers 
  url: /organizers/
- text: 2020 Workshop
  url: /past/2020/
