name: NeurIPS 2020 Workshop on Muslims in ML
markdown: kramdown

navigation:
- text: Description
  url: /
- text: Talks 
  url: /talks/
- text: Schedule 
  url: /schedule/
- text: Registration 
  url: /registration/
- text: Organizers 
  url: /organizers/
